initial_branch: main
solved_branch: quarkus-migration
commit_id: 51a918acb7f6b6e74d86963fd354cd68adda92ac
new_commitId: 9fd5a29585234b32cdd81cea71d71408760c489b
timestamp: 1707242434
repo: https://github.com/mathianasj/eap-coolstore-monolith.git